apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management-service
  namespace: bccs
  labels:
    app: product-management-service
    tier: write
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-management-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: product-management-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: product-management-service
          image: registry.local/bccs/product-management-service:4.0.0
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: product-management-config
            - secretRef:
                name: bccs-secrets
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 15
