apiVersion: v1
kind: Service
metadata:
  name: product-management-service
  namespace: bccs
  labels:
    app: product-management-service
spec:
  type: ClusterIP
  selector:
    app: product-management-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
