apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-config
  namespace: bccs
data:
  THIRD_PARTY_AUTH_URL: "https://auth.partner.example.com"
  SPRING_PROFILES_ACTIVE: "prod"
  SERVICE_ENV: "k8s"
