apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: bccs
  labels:
    app: integration-service
spec:
  type: ClusterIP
  selector:
    app: integration-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
