apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
  namespace: bccs
  labels:
    app: product-catalog-service
    tier: read
spec:
  replicas: 4
  selector:
    matchLabels:
      app: product-catalog-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: product-catalog-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: product-catalog-service
          image: registry.local/bccs/product-catalog-service:4.0.0
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: product-catalog-config
            - secretRef:
                name: bccs-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "768Mi"
            limits:
              cpu: "2000m"
              memory: "1536Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 15
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: product-catalog-service
