apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: bccs
  labels:
    app: product-catalog-service
spec:
  type: ClusterIP
  selector:
    app: product-catalog-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
